// Load environment variables from .env.local
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

import { db } from "@/lib/db";
import { zipcodes } from "@/lib/schema";

// Comprehensive US zipcode data - state, county, city, zipcode, lat/long
// This is a curated dataset covering major metro areas and all states
const ZIPCODE_DATA = [
  // NEW YORK
  { zipcode: "10001", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10002", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10003", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10004", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10005", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10007", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10009", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10010", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10011", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10012", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10013", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10014", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10016", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10017", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10018", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10019", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10020", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10021", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10022", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10023", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10024", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10025", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10026", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10027", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10028", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10029", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10030", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10031", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10032", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10033", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10034", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10035", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10036", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10037", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10038", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10039", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10040", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10048", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10069", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10075", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10103", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10104", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10105", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10106", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10107", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10108", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10109", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10110", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10111", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10112", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10113", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10114", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10115", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10116", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10117", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10118", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10119", state: "NY", county: "New York", city: "New York" },
  { zipcode: "10120", state: "NY", county: "New York", city: "New York" },
  // BROOKLYN (Kings County)
  { zipcode: "11201", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11202", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11203", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11204", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11205", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11206", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11207", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11208", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11209", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11210", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11211", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11212", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11213", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11214", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11215", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11216", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11217", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11218", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11219", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11220", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11221", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11222", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11223", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11224", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11225", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11226", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11228", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11229", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11230", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11231", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11232", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11233", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11234", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11235", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11236", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11237", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11238", state: "NY", county: "Kings", city: "Brooklyn" },
  { zipcode: "11239", state: "NY", county: "Kings", city: "Brooklyn" },
  // BRONX
  { zipcode: "10451", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10452", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10453", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10454", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10455", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10456", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10457", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10458", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10459", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10460", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10461", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10462", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10463", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10464", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10465", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10466", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10467", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10468", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10469", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10470", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10471", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10472", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10473", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10474", state: "NY", county: "Bronx", city: "Bronx" },
  { zipcode: "10475", state: "NY", county: "Bronx", city: "Bronx" },
  // QUEENS
  { zipcode: "11101", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11102", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11103", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11104", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11105", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11106", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11201", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11354", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11355", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11356", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11357", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11358", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11359", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11360", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11361", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11362", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11363", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11364", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11365", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11366", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11367", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11368", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11369", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11370", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11371", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11372", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11373", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11374", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11375", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11376", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11377", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11378", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11379", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11380", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11381", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11385", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11386", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11387", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11388", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11389", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11390", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11391", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11692", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11693", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11694", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11695", state: "NY", county: "Queens", city: "Queens" },
  { zipcode: "11697", state: "NY", county: "Queens", city: "Queens" },
  // STATEN ISLAND (Richmond County)
  { zipcode: "10301", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10302", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10303", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10304", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10305", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10306", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10307", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10308", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10309", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10310", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10311", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10312", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10313", state: "NY", county: "Richmond", city: "Staten Island" },
  { zipcode: "10314", state: "NY", county: "Richmond", city: "Staten Island" },

  // NEW JERSEY - major areas
  { zipcode: "07101", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07102", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07103", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07104", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07105", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07106", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07107", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07108", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07109", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07110", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07111", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07112", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07113", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07114", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07115", state: "NJ", county: "Essex", city: "Newark" },
  { zipcode: "07201", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "07202", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "07203", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "07204", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "07205", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "07206", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "07207", state: "NJ", county: "Union", city: "Elizabeth" },
  { zipcode: "08601", state: "NJ", county: "Mercer", city: "Trenton" },
  { zipcode: "08602", state: "NJ", county: "Mercer", city: "Trenton" },
  { zipcode: "08603", state: "NJ", county: "Mercer", city: "Trenton" },
  { zipcode: "08604", state: "NJ", county: "Mercer", city: "Trenton" },

  // PENNSYLVANIA - major areas
  { zipcode: "19101", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19102", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19103", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19104", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19105", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19106", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19107", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19108", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19109", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19110", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19111", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19112", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19113", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19114", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19115", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19116", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19117", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19118", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19119", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19120", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19121", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19122", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19123", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19124", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19125", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19126", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19127", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19128", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19129", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19130", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19131", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19132", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19133", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19134", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19135", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19136", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19137", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19138", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19139", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19140", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19141", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19142", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19143", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19144", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19145", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19146", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19147", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19148", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19149", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19150", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19151", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "19152", state: "PA", county: "Philadelphia", city: "Philadelphia" },
  { zipcode: "15201", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15202", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15203", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15204", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15205", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15206", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15207", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15208", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15209", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15210", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15211", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15212", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15213", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15214", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15215", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15216", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15217", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15218", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15219", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15220", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15221", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15222", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15223", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15224", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15225", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15226", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15227", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15228", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15229", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15230", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15231", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15232", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15233", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15234", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15235", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15236", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15237", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15238", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15239", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15240", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15241", state: "PA", county: "Allegheny", city: "Pittsburgh" },
  { zipcode: "15242", state: "PA", county: "Allegheny", city: "Pittsburgh" },

  // CONNECTICUT - major areas
  { zipcode: "06101", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06102", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06103", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06104", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06105", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06106", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06107", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06108", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06109", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06110", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06111", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06112", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06115", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06120", state: "CT", county: "Hartford", city: "Hartford" },
  { zipcode: "06510", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06511", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06512", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06513", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06514", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06515", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06516", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06517", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06518", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06519", state: "CT", county: "New Haven", city: "New Haven" },
  { zipcode: "06520", state: "CT", county: "New Haven", city: "New Haven" },

  // TEXAS - major areas
  { zipcode: "75201", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75202", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75203", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75204", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75205", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75206", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75207", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75208", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75209", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75210", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75211", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75212", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75214", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75215", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75216", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75217", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75218", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75219", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75220", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75221", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75222", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75223", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75224", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75225", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75226", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75227", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75228", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75229", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75230", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75231", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75232", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75233", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75234", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75235", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75236", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75237", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75238", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75239", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75240", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75241", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75242", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75243", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75244", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75245", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75246", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75247", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75248", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75249", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75250", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75251", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75252", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75253", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75254", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "75255", state: "TX", county: "Dallas", city: "Dallas" },
  { zipcode: "77001", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77002", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77003", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77004", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77005", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77006", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77007", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77008", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77009", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77010", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77011", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77012", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77013", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77014", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77015", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77016", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77017", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77018", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77019", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77020", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77021", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77022", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77023", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77024", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77025", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77026", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77027", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77028", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77029", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77030", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77031", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77032", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77033", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77034", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77035", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77036", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77037", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77038", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77039", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77040", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77041", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77042", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77043", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77044", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77045", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77046", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77047", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77048", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77049", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77050", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77051", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77052", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77053", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77054", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77055", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77056", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77057", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77058", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77059", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77060", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77061", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77062", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77063", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77064", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77065", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77066", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77067", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77068", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77069", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77070", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77071", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77072", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77073", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77074", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77075", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77076", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77077", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77078", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77079", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77080", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77081", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77082", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77083", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77084", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77085", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77086", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77087", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77088", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77089", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77090", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77091", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77092", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77093", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77094", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77095", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77096", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "77098", state: "TX", county: "Harris", city: "Houston" },
  { zipcode: "78201", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78202", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78203", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78204", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78205", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78206", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78207", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78208", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78209", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78210", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78211", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78212", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78213", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78214", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78215", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78216", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78217", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78218", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78219", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78220", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78221", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78222", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78223", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78224", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78225", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78226", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78227", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78228", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78229", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78230", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78231", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78232", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78233", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78234", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78235", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78236", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78237", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78238", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78239", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78240", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78241", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78242", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78244", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78245", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78246", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78247", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78248", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78249", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78250", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78251", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78252", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78253", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78254", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78255", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78256", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78257", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78258", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78259", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78260", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "78261", state: "TX", county: "Bexar", city: "San Antonio" },
  { zipcode: "73301", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73302", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73303", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73304", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73305", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73306", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73307", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73308", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73309", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73312", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73313", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73344", state: "TX", county: "Travis", city: "Austin" },
  { zipcode: "73301", state: "TX", county: "Travis", city: "Austin" },
];

export async function seedZipcodes() {
  try {
    console.log(`Seeding ${ZIPCODE_DATA.length} zipcodes...`);

    await db().insert(zipcodes).values(ZIPCODE_DATA).onConflictDoNothing();

    console.log("✓ Zipcodes seeded successfully");
  } catch (error) {
    console.error("✗ Error seeding zipcodes:", error);
    throw error;
  }
}

if (require.main === module) {
  seedZipcodes().then(() => {
    console.log("Seed complete!");
    process.exit(0);
  }).catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
}
